<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Volcano</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <NoWarn>$(NoWarn);CA1416;WFO1000</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.21.9" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part1" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part10" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part2" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part3-fragment1" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part3-primary" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part4" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part5-fragment1" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part5-fragment2" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part5-primary" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part6" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part7-fragment1" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part7-primary" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part8" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part9-fragment1" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part9-fragment2" Version="2.10.0" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64-part9-primary" Version="2.10.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SharpZipLib" Version="1.4.0" />
    <PackageReference Include="SkiaSharp" Version="2.88.6" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="2.88.6" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.6" />
    <PackageReference Include="TorchSharp" Version="0.107.0" />
    <PackageReference Include="TorchSharp-cuda-windows" Version="0.107.0" />
  </ItemGroup>
</Project>